# Taken from LibreHardwareMonitor https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/.github/workflows/main.yml

name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: 'latest'

      - name: NuGet restore
        run: nuget restore Genius.sln

      - name: Build
        run: msbuild Genius.sln -p:Configuration=Release -m

      - name: Publish net60
        uses: actions/upload-artifact@v2
        id: publish_net6
        with:
          name: genius-net6
          path: |
            Genius/bin/Release/net6.0

      - name: Publish client net60
        uses: actions/upload-artifact@v2
        id: publish_client_net6
        with:
          name: genius-client-net6
          path: |
            Genius.Client/bin/Release/net6.0